worker_processes auto;
events { worker_connections 1024; }
http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    limit_req_zone $binary_remote_addr zone=login:10m rate=10r/m;
    upstream flask { server app:5000; keepalive 8; }
    server {
        listen 80;
        return 301 https://$host$request_uri;
    }
    server {
        listen 443 ssl;
        server_name cms.company.com localhost;
        client_max_body_size 50M;
        ssl_certificate     /etc/nginx/certs/server/server.crt;
        ssl_certificate_key /etc/nginx/certs/server/server.key;
        ssl_client_certificate /etc/nginx/certs/ca/ca.crt;
        ssl_verify_client optional;
        ssl_protocols TLSv1.2 TLSv1.3;
        add_header Strict-Transport-Security "max-age=63072000" always;
        proxy_set_header X-SSL-Client-Verify $ssl_client_verify;
        proxy_set_header X-SSL-Client-DN     $ssl_client_s_dn;
        proxy_set_header X-SSL-Client-Serial $ssl_client_serial;
        proxy_set_header X-Forwarded-For     $proxy_add_x_forwarded_for;
        proxy_set_header Host                $host;
        location /auth/login { limit_req zone=login burst=5 nodelay; proxy_pass http://flask; }
        location / { proxy_pass http://flask; proxy_read_timeout 60s; }
    }
}
